name: example
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  gradient_widgets:
    path: ../
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any

flutter:

  uses-material-design: true
